name: Deploy games pages
on:
  - workflow_dispatch
permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  MOBY_API_KEY: '${{ secrets.MOBY_API_KEY }}'

jobs:
  do-the-thing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3
          cache: pip
      - name: PIP Dependencies
        run: pip install -r requirements.txt
      - name: Google Authentication
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_AUTH }}'
      - name: Create schedule file
        run: python schedule.py
        env:
          SPREADSHEET_ID: '${{ vars.SCHEDULE_SPREADSHEET_ID }}'
          SPREADSHEET_NAME: '${{ vars.SCHEDULE_SPREADSHEET_NAME }}'
          SPREADSHEET_RANGE: '${{ vars.SCHEDULE_SPREADSHEET_RANGE }}'
      - name: Create deployment package
        run: |
          mkdir site
          mv *.html *.css images site/
          chmod -R +rX site
      - name: Upload deployment artifact
        uses: actions/upload-pages-artifact@v3
        with:
          page: site
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4